version: "3.8"

services:
  api1:
    build:
      context: .
    hostname: api1
    container_name: api1
    expose:
      - 6000
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '0.8GB'

  api2:
    build:
      context: .
    hostname: api2
    container_name: api2
    expose:
      - 6000
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: '0.8GB'

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.4GB'
  
  redis:
    image: redis:latest
    container_name: redis
    command: >
      redis-server 
        --appendonly no
        --tcp-keepalive 0
    ports:
      - 6370:6379
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.6GB'
